### ISSUE TITLE
Weird pagination at jstips.co

### ISSUE THREAD

**Issue by ro0NL** [loverajoel/jstips#285]
Hi,

Just a minor issue.. but i noticed the paginator at http://www.jstips.co sometimes show 3 results per page and sometimes 4 results per page..

As we speak:
- http://www.jstips.co/3/ shows 4 results
- http://www.jstips.co/4/ shows 3 results
- http://www.jstips.co/5/ shows 3 results
- http://www.jstips.co/6/ shows 4 results
- http://www.jstips.co/7/ shows 3 results

Also noticed that page #1 in the paginator links to the `previous` page instead of the `first` page... ;-)

My2cents.

**Comment by ro0NL** [comment]
Perhaps also start at index 1 rather than index 0 for the tip count..

Tip #0 feels a bit weird to me (http://www.jstips.co/15/)

**Comment by zenopopovici** [comment]
We'll look into that. Thanks.

**Comment by loverajoel** [comment]
@ro0NL yes, so weird, I will check.

thanks

**Comment by loverajoel** [comment]
I fixed that, now we are showing 10 per page, but still is strange

**Comment by ro0NL** [comment]
@loverajoel the 1st page link is still wrong...

http://www.jstips.co/3/

Both page 1 & 2 are linking to page 2.

**Comment by loverajoel** [comment]
@ro0NL true, I will check, thanks

**Comment by zenopopovici** [comment]
Merged this issue here: https://github.com/loverajoel/jstips/issues/223

**Comment by zenopopovici** [comment]
This si fixed.
